### ISSUE TITLE
While pressing on UI objects, the waves animation getting halt in iOS app.

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [alankarmisra/SwiftSiriWaveformView#14] opened 2017-05-25 08:14 UTC
Thanks for great framework. Really helped me, but I am facing one strange issue over there.
While animation going on, if I press any where on UI objects like tableview or buttons, etc, the animation getting halting.But, after I release touch on UI, its again stating animation. How to fix this?

I am using this framework in my iOS app.

**Comment by alankarmisra** [comment] 2017-05-25 15:30
It's hard to imagine what the issue might be without looking at the code. Could you distill your project down to it's bare essentials that would reproduce the issue and attach it on here? I don't think the issue has anything to do with the Waveform view control though cause I noticed you've had similar issues with a waveform control from a different author.

**Comment by AnilkumarRabhasa** [comment] 2017-05-26 06:51
@alankarmisra the thing is, I am showing waves animation, its working fine, but If i pressed any where in UI, its getting Halting thats the issue. After I release that pressing, its working again.

Can you please do some suggestions to not stop/halting that animation even if I click on anywhere UI.

**Comment by alankarmisra** [comment] 2017-05-26 08:33
There is nothing in the component that stops animations when some other component has focus. It should continue animating. But since that isn't how it works for you, I need to see your project code to find the issue. Since you're having the same issue with my component and a component by another author, chances are that the issue is in your code. Which is why I'm asking for a bare minimum project. Or you could ask on Stackoverflow.

**Comment by alankarmisra** [comment] 2017-08-08 10:06
Closing this since I cannot replicate this problem and haven't been provided any code that can.

**Closed as completed by alankarmisra** 2017-08-08 10:06 UTC
Labels: question
